layout_spectrum: 0.8595745
color:
  saturation: 0.6893617
  lightness: 0.3851064
  brandStrength: 1
  rhythmicContrast: 0.7765958
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.7744681
name: Maybe Just Maybe...
